name: build

on:
  push:
    branches: [main]

  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  database:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          path: repo

      - name: Clone github/advisory-database
        uses: actions/checkout@v3
        with:
          repository: 'github/advisory-database'
          path: advisory-database

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Create JSON
        run: |
          mkdir -p public/
          python repo/.ci-helpers/repo2json.py -i advisory-database/advisories/github-reviewed -o public/db.json

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Update db.json'
          force_orphan: true
